export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS";
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL";
export const ROOM_DETAILS_SUCCESS = "ROOMS_DETAILS_SUCCESS";
export const ROOM_DETAILS_FAIL = "ROOMS_DETAILS_FAIL";
// export const SEARCHED_ROOM_SUCCESS = "SEARCHED_ROOMS_SUCCESS";
// export const SEARCHED_ROOM_FAIL = "SEARCHED_ROOMS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
